-- local present, trouble = pcall(require, "trouble")
-- if not present then
--   return
-- end
--
-- trouble.setup {
--   height = 12,
--   mode = "document_diagnostics",
--   use_diagnostic_signs = true,
--   action_keys = {
--     refresh = "r",
--     toggle_mode = "m",
--     toggle_preview = "P",
--     close_folds = "zc",
--     open_folds = "zo",
--     toggle_fold = "zt"
--   }
-- }
