eval "$(starship init zsh)"
eval "$(direnv hook zsh)"

alias be="cd ~/Projects/mt-api/"
alias fe="cd ~/Projects/mt-app/"

wt-co () {
	local current_dir=$(basename "$PWD")
	local selected_branch=$(git branch -r | sed 's/origin\///' | sed 's/^[* ]*//' | grep -v HEAD | sort -u | fzf --prompt="Select branch: " --height=40%)
	if [[ -z "$selected_branch" ]]
	then
		echo "No branch selected."
		return 1
	fi
	local worktree_base="../${current_dir}-worktrees"
	local worktree_path="${worktree_base}/${selected_branch}"
	mkdir -p -p "$worktree_base"
	echo "Creating worktree at: $worktree_path"
	git worktree add "$worktree_path" "origin/$selected_branch"

	cd "$worktree_path"
  git co $selected_branch
	echo "Switched to worktree: $selected_branch"
}

wt-api-cp () {
  local project_home="~/Projects/mt-api"
  local config_source_dir="src/main/java/conf"
  echo "Copying files"
  cp "${project_home}/${config_source_dir}/development.conf" "./${config_source_dir}"
  # cp ".tool-versions" "${worktree_path}"
  cp -r "${project_home}/.idea" .
}

wt-app-cp () {
  local project_home="~/Projects/mt-app"
  echo "Copying files"
  # cp ".tool-versions" "${worktree_path}"
  cp -r "${project_home}/.idea" .
}


wt-cd () {
	if ! git rev-parse --git-dir > /dev/null 2>&1
	then
		echo "Error: Not in a git repository"
		return 1
	fi
	if ! command -v fzf > /dev/null 2>&1
	then
		echo "Error: fzf is not installed"
		return 1
	fi
	local worktrees=$(git worktree list --porcelain | grep -E "^worktree " | sed 's/^worktree //' | grep -v "$(git rev-parse --show-toplevel)$")
	if [[ -z "$worktrees" ]]
	then
		echo "No additional worktrees found"
		return 0
	fi
	local selected=$(echo "$worktrees" | fzf --multi --prompt="Select worktrees to navigate to: " --height=40% --reverse --border)
	if [[ -z "$selected" ]]
	then
		echo "No worktrees selected"
		return 0
	fi
  cd $selected
	pwd
}

wt-kill () {
	if ! git rev-parse --git-dir > /dev/null 2>&1
	then
		echo "Error: Not in a git repository"
		return 1
	fi
	if ! command -v fzf > /dev/null 2>&1
	then
		echo "Error: fzf is not installed"
		return 1
	fi
	local worktrees=$(git worktree list --porcelain | grep -E "^worktree " | sed 's/^worktree //' | grep -v "$(git rev-parse --show-toplevel)$")
	if [[ -z "$worktrees" ]]
	then
		echo "No additional worktrees found"
		return 0
	fi
	local selected=$(echo "$worktrees" | fzf --multi --prompt="Select worktrees to remove: " --height=40% --reverse --border)
	if [[ -z "$selected" ]]
	then
		echo "No worktrees selected"
		return 0
	fi
	echo "$selected" | while IFS= read -r worktree
	do
		echo "Removing worktree: $worktree"
		if git worktree remove "$worktree"
		then
			echo "✓ Removed: $worktree"
		else
			echo "✗ Failed to remove: $worktree"
		fi
	done
	echo "Done"
}
# eval "$(/opt/homebrew/bin/mise activate zsh)"


# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
